import {TableCardColumn, TableCardRow} from "../../styled/tableCard";
import {TableCardUserComponent} from "./TableCardUserComponent";
import {TableCardFreedomTime} from "./TableCardFreedomTime";
import React from "react";
import {LastColumn} from "../../utiles/lastColumn";

export function TableThursday() {
    return (
        <TableCardRow
            active
        >
            <TableCardColumn>
                <TableCardUserComponent
                    color={'#FE8900;'}
                    width={'42px'}
                    name={'Тельнова Злата'}
                    borderHeight={'70px'}
                    borderBottom={'0'}
                    border={'none'}
                />
                <TableCardFreedomTime
                    color={'#00459B;'}
                    position={'0'}
                    first
                    width={'45px'}
                    positionLeft={'0'}
                    border={'none'}
                />
                <TableCardUserComponent
                    color={'#DF1B7D;'}
                    width={'42px'}
                    name={'Тельнова Злата'}
                    borderHeight={'76px'}
                    borderBottom={'0'}
                    border={'none'}
                />
            </TableCardColumn>
            <TableCardFreedomTime
                color={'#00459B;'}
                position={'51px'}
                width={'45px'}
                positionLeft={'51px'}
            />
            <TableCardFreedomTime
                color={'#00459B;'}
                position={'51px'}
                width={'45px'}
                positionLeft={'51px'}
            />
            <TableCardColumn>
                <TableCardUserComponent
                    color={'#FE8900;'}
                    width={'42px'}
                    name={'Тельнова Злата'}
                    borderHeight={'74px'}
                    borderBottom={'5px'}
                    border={'none'}
                    last
                />
                <TableCardFreedomTime
                    color={'#00459B;'}
                    position={'0'}
                    width={'45px'}
                    positionLeft={'0'}
                    border={'none'}
                />
                <TableCardFreedomTime
                    color={' #DF1B7D;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
            </TableCardColumn>
            <TableCardColumn>
                <TableCardFreedomTime
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardFreedomTime
                    color={'#00459B;'}
                    position={'-0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardFreedomTime
                    color={' #DF1B7D;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
            </TableCardColumn>
            <TableCardColumn>
                <TableCardFreedomTime
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardUserComponent
                    color={'#00459B;'}
                    width={'42px'}
                    name={'Тельнова Злата'}
                    borderBottom={'6px'}
                    borderHeight={'71px'}
                    border={'none'}
                    last
                />
                <TableCardFreedomTime
                    color={' #DF1B7D;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
            </TableCardColumn>
            <TableCardColumn>
                <TableCardFreedomTime
                    color={'#FE8900;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardFreedomTime
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardFreedomTime
                    color={' #DF1B7D;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
            </TableCardColumn>
            <TableCardColumn>
                <TableCardFreedomTime
                    color={'#FE8900;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardFreedomTime
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardFreedomTime
                    color={' #DF1B7D;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
            </TableCardColumn>
            <TableCardColumn>
                <TableCardFreedomTime
                    color={'#FE8900;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardFreedomTime
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardFreedomTime
                    color={' #DF1B7D;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
            </TableCardColumn>
            <TableCardColumn>
                <TableCardFreedomTime
                    color={'#FE8900;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardFreedomTime
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardFreedomTime
                    color={' #DF1B7D;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
            </TableCardColumn>
            <TableCardColumn>
                <TableCardFreedomTime
                    color={'#FE8900;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardFreedomTime
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardFreedomTime
                    color={' #DF1B7D;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
            </TableCardColumn>
            <TableCardColumn>
                <TableCardFreedomTime
                    color={'#FE8900;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                    height={'28px'}
                    bottom={'1px'}
                />
                <TableCardFreedomTime
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                />
                <TableCardFreedomTime
                    color={' #DF1B7D;'}
                    position={'0'}
                    width={'45px'}
                    border={'none'}
                    positionLeft={'0'}
                    height={'28px'}
                    bottom={'1px'}
                />
            </TableCardColumn>
            <TableCardColumn>
                <TableCardUserComponent
                    color={'#FE8900;'}
                    width={'42px'}
                    name={'Эрик 6 лет'}
                    border={'none'}
                    borderHeight={'71px'}
                    borderBottom={'1px'}
                />
                <TableCardFreedomTime
                    position={'0'}
                    width={'45px'}
                    positionLeft={'0'}
                    border={'none'}
                />
                <TableCardUserComponent
                    color={'#DF1B7D;'}
                    width={'42px'}
                    name={'Эрик 6 лет'}
                    borderHeight={'71px'}
                    borderBottom={'1px'}
                    border={'none'}
                />
            </TableCardColumn>
            <TableCardFreedomTime/>
            <TableCardFreedomTime/>
            <TableCardFreedomTime/>
            <TableCardFreedomTime/>
            <TableCardFreedomTime/>
            <TableCardFreedomTime/>
            <TableCardFreedomTime/>
            <TableCardFreedomTime/>
            <LastColumn
                height={'20px'}
            />
            <LastColumn
                height={'20px'}
            />
            <LastColumn/>
        </TableCardRow>
    )
}